import sys
from typing import SupportsComplex, SupportsFloat

e: float
pi: float
if sys.version_info >= (3, 6):
    inf: float
    infj: complex
    nan: float
    nanj: complex
    tau: float

_C = SupportsFloat|SupportsComplex|complex


def cos(__z: _C) -> complex: ...
def exp(__z: _C) -> complex: ...
def log(__x: _C, __y_obj: _C = ...) -> complex: ...
def log10(__z: _C) -> complex: ...
def phase(__z: _C) -> float: ...
def polar(__z: _C) -> tuple[float, float]: ...
def rect(__r: float, __phi: float) -> complex: ...
def sin(__z: _C) -> complex: ...
def sqrt(__z: _C) -> complex: ...
