import sys
from _typeshed import ReadableBuffer
from typing import AbstractSet, Optional

class sha256(object):
    def __init__(self, data: ReadableBuffer = ...) -> None: ...
    def digest(self) -> bytes: ...
    def update(self, __data: ReadableBuffer) -> None: ...
