# make_stub_files: Wed 03 Feb 2021 at 08:14:26
class Event:
    def __init__(self) -> None: ...
    def is_set(self) -> Any: ...
        #   0: return self.state
        # ? 0: return self.state
    def set(self) -> None: ...
    def clear(self) -> None: ...
