# make_stub_files: Wed 03 Feb 2021 at 08:14:26
def runner(waiter: Any, aw: Any) -> None: ...
def wait_for_ms(aw: Any, timeout: Any) -> Any: ...
    #   0: return wait_for(aw,timeout,core.sleep_ms)
    # ? 0: return wait_for(aw, timeout, core.sleep_ms)
