# make_stub_files: Wed 03 Feb 2021 at 08:14:26
class Stream:
    def __init__(self, s: Any, e: Any={}) -> None: ...
    def get_extra_info(self, v: Any) -> Any: ...
        #   0: return self.e[v]
        # ? 0: return self.e[v]
    def close(self) -> None: ...
    def write(self, buf: Any) -> None: ...
class Server:
    def close(self) -> None: ...
