from typing import Any

class Event:
    def __init__(self) -> None: ...
    def is_set(self) -> Any: ...
        #   0: return self.state
        # ? 0: return self.state
    def set(self) -> None: ...
    def clear(self) -> None: ...
